spring:
  application:
    name: mcb-admim-micro-service
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: "*"