spring:
  application:
    name: Gateway-Service
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: "*"

server:
  port: 9090